# Base configs
baseurl: ""
url: "http://photography.ramswaroop.me"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Bela Mondo"
subtitle: "Foto Blogo"
author: "Erraimuna Gorrotxategi"
bio: "Mi amas foton."
social_urls:
  instagram: "https://www.instagram.com/ramswarooppatra"
 
  
